---
- name: Install Mysql package
  apt: name={{ item }} state=latest
  with_items:
    - mysql-client
    - mysql-server
    - python-mysqldb
    - libmysqlclient-dev
    - libmysqld-dev

- name: Create Mysql configuration file
  template: src=my.cnf.j2 dest=/etc/my.cnf
  notify:
    - restart mysql

- name: Start Mysql Service
  service: name=mysql state=started enabled=yes
